[package]
name = "enarx-keepldr"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
license = "Apache-2.0"
edition = "2018"
build = "build.rs"
homepage = "https://github.com/enarx/enarx-keepldr"
repository = "https://github.com/enarx/enarx-keepldr"
description = "Enarx Keep Loader"
readme = "README.md"
keywords = ["sgx", "sev", "kvm", "tee"]
categories = ["os", "os::linux-apis", "network-programming", "hardware-support"]
exclude = [ ".gitignore", ".github/*" ]
include = [ "src", "internal" ]

[badges]
# See https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
github = { repository = "enarx/enarx-keepldr", workflow = "test" }
#github = { repository = "enarx/enarx-keepldr", workflow = "lint" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "enarx/enarx-keepldr" }
is-it-maintained-open-issues = { repository = "enarx/enarx-keepldr" }

[features]
default = ["backend-sev"]

backend-nil = []
backend-kvm = ["x86_64", "kvm-bindings", "kvm-ioctls"]
backend-sev = ["sev", "backend-kvm", "koine"]
backend-sgx = ["sgx"]

[dependencies]
sev = { git = "https://github.com/enarx/sev", features = ["openssl"], optional = true }
sgx = { git = "https://github.com/enarx/sgx", rev = "5292e53", features = ["asm", "crypto"], optional = true }
koine = { git = "https://github.com/enarx/koine", optional = true }
x86_64 = { version = "0.11", default-features = false, features = ["stable"], optional = true }
kvm-bindings = { version = "0.3", optional = true }
kvm-ioctls = { version = "0.5", optional = true }
primordial = "0.1"
structopt = "0.3"
colorful = "0.2"
codicon = "3.0"
mmarinus = "0.2"
nbytes = "0.1"
anyhow = "1.0"
goblin = "0.3"
libc = "0.2"
lset = "0.1"
protobuf = "2.18"
serde = "1.0"
serde_cbor = "0.11"

[build-dependencies]
cc = "1.0"
walkdir = "2"
protobuf-codegen-pure = "2.3"

[dev-dependencies]
process_control = "2.0"
serial_test = "0.5"
