[package]
name = "shim-sgx"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sgx"
test = false

[dependencies]
sallyport = { git = "https://github.com/enarx/sallyport", rev = "3872722009428b7002f8b703fd8c38958572952c", features=[ "asm" ] }
enarx-heap = { git = "https://github.com/enarx/enarx-heap", rev = "9cbfb3367edd4aa17f4a7409ea0c0f7d83fa8ce3" }
rcrt1 = { git = "https://github.com/enarx/rcrt1", rev = "b28f711" }
x86_64 = { git = "https://github.com/npmccallum/x86_64", branch = "errors" }
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
goblin = { version = "0.4", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
const-default = "0.1"
primordial = "0.3.0"
flagset = "0.4"
xsave = "0.1.1"
nbytes = "0.1"
noted = "0.1"
lset = "0.2"

[profile.dev.package.rcrt1]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
