[package]
name = "shim-sgx"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "shim-sgx"
test = false

[dependencies]
sallyport = { path = "../sallyport", default-features = false }
rcrt1 = { path = "../rcrt1" }
sgx-heap = { path = "../sgx-heap" }
syscall = { path = "../syscall"}
untrusted = { path = "../untrusted"}
compiler_builtins = { version = "0.1", default-features = false, features = [ "mem" ] }
sgx = { git = "https://github.com/enarx/sgx", rev = "5292e53" }
goblin = { version = "0.3", default-features = false, features = [ "elf64" ] }
crt0stack = { version = "0.1", default-features = false }
libc = { version = "0.2", default-features = false }
primordial = "0.1"
nbytes = "0.1"
lset = "0.1"

[profile.dev.package.rcrt1]
opt-level = 3

[build-dependencies]
cc = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
incremental = false
lto = true
