on: [push, pull_request]
name: lint
jobs:
  fmt:
    name: cargo fmt (${{ matrix.crate.name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=${{ matrix.crate.path }} -- --check
    strategy:
      fail-fast: false
      matrix:
        crate:
          - {name: enarx-keepldr, path: Cargo.toml}
          - {name: rcrt1, path: internal/rcrt1/Cargo.toml}
          - {name: sallyport, path: internal/sallyport/Cargo.toml}
          - {name: shim-sgx, path: internal/shim-sgx/Cargo.toml}
          - {name: shim-sev, path: internal/shim-sev/Cargo.toml}

  clippy-all:
    name: clippy::all (${{ matrix.crate.name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "The following files do not #![deny(clippy::all)]:"
          ! git grep -LF "#![deny(clippy::all)]" -- "${{ matrix.crate.path }}"
    strategy:
      fail-fast: false
      matrix:
        crate:
          - {name: enarx-keepldr, path: src/main.rs}
          - {name: rcrt1, path: internal/rcrt1/src/lib.rs}
          - {name: sallyport, path: internal/sallyport/src/lib.rs}
          - {name: shim-sgx, path: internal/shim-sgx/src/main.rs}
          - {name: shim-sev, path: internal/shim-sev/src/main.rs}

  clippy:
    name: cargo clippy (${{ matrix.crate.name }})
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt update
      - run: sudo apt install -y musl-tools
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: nightly
          profile: minimal
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.crate.target }} --manifest-path=${{ matrix.crate.path }} -- -D warnings
    strategy:
      fail-fast: false
      matrix:
        crate:
          - {name: enarx-keepldr, path: Cargo.toml}
          - {name: sallyport, path: internal/sallyport/Cargo.toml}
          - name: rcrt1
            path: internal/rcrt1/Cargo.toml
            target: --target=x86_64-unknown-linux-musl
          - name: shim-sgx
            path: internal/shim-sgx/Cargo.toml
            target: --target=x86_64-unknown-linux-musl
          - name: shim-sev
            path: internal/shim-sev/Cargo.toml
            target: --target=x86_64-unknown-linux-musl

  readme:
    name: cargo readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - run: cargo install cargo-readme
      - run: cargo readme > README.md && git diff --exit-code

  deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
